name: ci-with-updating-snapshots

on: [pull_request]

jobs:
  snapshots:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'renovate[bot]' }}

    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --non-interactive

      - name: Lint
        run: yarn lint

      - name: Test with update-snapshots
        run: AVA_FORCE_CI="not-ci" yarn ava --verbose --update-snapshots

      - name: Test
        run: yarn test

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.15.0
        env:
          HUSKY: 0
        with:
          commit_message: "test: update snapshots"
          file_pattern: "**/*.snap **/*.md"
